### ISSUE TITLE
Installing triton error (Mac), can it be ignored ?

### ISSUE THREAD

**Issue by AlChico85** [MackinationsAi/sd-webui-udav2#1]
Hi, first at all, thank you for the extension.

I running A1111 on a Mac Studio M2 Max - installed your sd-webui-udav2 extension.
So far, it works like it should as far as i can tell, but i alway get a error message related to the udav2 extension in the Log once i start A1111.

`*** Error running install.py for extension /Volumes/T7Shield/stable-diffusion-webui/extensions/sd-webui-udav2.
*** Command: "/Volumes/T7Shield/stable-diffusion-webui/venv/bin/python3.10" "/Volumes/T7Shield/stable-diffusion-webui/extensions/sd-webui-udav2/install.py"
*** Error code: 1
*** stdout: Installing triton
*** 
*** stderr: Traceback (most recent call last):
***   File "/Volumes/T7Shield/stable-diffusion-webui/extensions/sd-webui-udav2/install.py", line 39, in <module>
***     launch.run_pip(f"install {triton_wheel}", "triton")
***   File "/Volumes/T7Shield/stable-diffusion-webui/modules/launch_utils.py", line 143, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "/Volumes/T7Shield/stable-diffusion-webui/modules/launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install triton.
*** Command: "/Volumes/T7Shield/stable-diffusion-webui/venv/bin/python3.10" -m pip install /Volumes/T7Shield/stable-diffusion-webui/extensions/sd-webui-udav2/triton-2.1.0-cp310-cp310-win_amd64.whl --prefer-binary
*** Error code: 1
*** stderr: ERROR: triton-2.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
*** 
`

Like i already said, udav2 is working on my Mac, but can i ignore the (triton) error or is it essential to something inside udav2 ?

**Comment by MackinationsAi** [comment]
You can ignore it, it is not essential for udav2 to work, it just gives you an acceleration boost w/ xformers.
