### ISSUE TITLE
Invalid value for parameter `type`: filepath. Please choose from one of: ['file', 'binary', 'bytes']

### ISSUE THREAD

**Issue by SnikeGear** [MackinationsAi/sd-webui-udav2#11]
Automatic1111

version: v1.10.1-4  •  python: 3.10.11  •  torch: 2.4.1+cu124  •  xformers: 0.0.28.dev895  •  gradio: 3.41.2

*** Error executing callback ui_tabs_callback for C:\pt3106\stable-diffusion-webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "C:\pt3106\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 280, in on_ui_tabs
        input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")
      File "C:\pt3106\stable-diffusion-webui\venv\lib\site-packages\gradio\templates.py", line 432, in __init__
        super().__init__(
      File "C:\pt3106\stable-diffusion-webui\venv\lib\site-packages\gradio\components\file.py", line 95, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: filepath. Please choose from one of: ['file', 'binary', 'bytes']

--- Before of last update no erros

**Comment by MackinationsAi** [comment]
If you go to the sd-webui-udav2 folder in your a1111 extensions folder, then to the scripts folder, open up upgraded_depth_anything_v2.py then go to line 280. - "C:\pt3106\stable-diffusion-webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py" Change the follow:

What you currently have in the "Batch_Image_Processing" tab - 
```
input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")
```
**to**
```
input_images = gr.Files(label="Upload Images", type="file", elem_id="img-display-input")
```

Simply remove 'path' from ```type="filepath"``` to make it ```type="file"``` & you should be back up & running again.

Doing this will resolve this error that you are getting. The reason it was changed is bc the latest updates that Gradio release from version gradio>=5.0.0 a lot of features & functionalities have been changed significantly. I see that you are running a1111 w/ gradio==3.41.2 [btw thank you for sharing your specs in the issue ticket, makes my job of debugging a LOT easier!]. Another alternative you can update gradio to the current version [however, if you go this route it will break a lot of the other current extensions you are using, so I wouldn't recommend it]. I'll be closing this ticket, though if you run into any more issues resolving this error, please don't hesitate to reach out!

**Comment by SnikeGear** [comment]
Hello, thank you for your very detailed and quick response. I applied the modification to the file indicated in that line and two others from the same file and everything worked correctly.

Thank you very much for your kind help.
