### ISSUE TITLE
UDAV2 tab is not visible in Forge

### ISSUE THREAD

**Issue by ropestra** [MackinationsAi/sd-webui-udav2#6]
<img width="772" alt="Issue12@2x" src="https://github.com/user-attachments/assets/aa6cd416-f887-4ca7-a055-b71910436643">

The UDAV2 tab is not visible in Forge, after unzipping and adding it to the extensions folder the tab is not available. As you can see in the screenshots, it is in the folder, even in the extensions list, but its tab is not visible in the menu.

**Comment by franklydegenerate** [comment]
Yeah, something must have happened with a file that it attempts to access, because even though Forge itself hasn't been updated in a long time, this extension stopped working all of a sudden. When it does work, it's incredible! Really excited to see it get fixed.

**Comment by tnotariano** [comment]
I found a solution, you need to edit some lines in stable-diffusion-webui-forge\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py. i think the problem arises from the new gradio update. **_This is for sd forge_**, but the code should be the same but it might be in different lines.

**1. replace lines 246-248 with:**

 input_image = gr.Image(label="Input Image", type='numpy', elem_id='img-display-input', height=794,) 
                depth_image_slider = gr.Image(label="Colourized Depth Map View", elem_id='img-display-output', height=794,)
                grey_depth_file_single = gr.Image(label="Greyscale Depth Map View", elem_id='img-display-output', height=794,) 


**2. replace line 268 with,** 

 input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")


**3. line 318 with,**

 input_videos = gr.Files(label="Input Videos", type="filepath", elem_id='img-display-input')


**4. finally, line 254,**  

 submit_single = gr.Button(value="Compute Depth for Single Image", variant="primary",)

sorry if this was tedious, I'm not familiar with how this works and it's my first time posting/editing.

**Comment by franklydegenerate** [comment]
> I found a solution, you need to edit some lines in stable-diffusion-webui-forge\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py. i think the problem arises from the new gradio update. **_This is for sd forge_**, but the code should be the same but it might be in different lines.
> 
> **1. replace lines 246-248 with:**
> 
> input_image = gr.Image(label="Input Image", type='numpy', elem_id='img-display-input', height=794,) depth_image_slider = gr.Image(label="Colourized Depth Map View", elem_id='img-display-output', height=794,) grey_depth_file_single = gr.Image(label="Greyscale Depth Map View", elem_id='img-display-output', height=794,)
> 
> **2. replace line 268 with,**
> 
> input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")
> 
> **3. line 318 with,**
> 
> input_videos = gr.Files(label="Input Videos", type="filepath", elem_id='img-display-input')
> 
> **4. finally, line 254,**
> 
> submit_single = gr.Button(value="Compute Depth for Single Image", variant="primary",)
> 
> sorry if this was tedious, I'm not familiar with how this works and it's my first time posting/editing.

Thank you for trying. Unfortunately, the extension still doesn't work for me. I get the following error even after replacing the lines you mentioned:

*** Error loading script: upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "E:\Private\stablediffusion\forge_new\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Private\stablediffusion\forge_new\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Private\stablediffusion\forge_new\webui\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py", line 4, in <module>
        from depth_anything_v2.dpt import DepthAnythingV2
    ModuleNotFoundError: No module named 'depth_anything_v2.dpt'

Edit: May be related to using wrong file - testing again
Edit2: This happens regardless of whether or not one uses the .7z or .zip file version of UDAV2 for forge.

**Comment by tnotariano** [comment]
> > I found a solution, you need to edit some lines in stable-diffusion-webui-forge\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py. i think the problem arises from the new gradio update. **_This is for sd forge_**, but the code should be the same but it might be in different lines.
> > **1. replace lines 246-248 with:**
> > input_image = gr.Image(label="Input Image", type='numpy', elem_id='img-display-input', height=794,) depth_image_slider = gr.Image(label="Colourized Depth Map View", elem_id='img-display-output', height=794,) grey_depth_file_single = gr.Image(label="Greyscale Depth Map View", elem_id='img-display-output', height=794,)
> > **2. replace line 268 with,**
> > input_images = gr.Files(label="Upload Images", type="filepath", elem_id="img-display-input")
> > **3. line 318 with,**
> > input_videos = gr.Files(label="Input Videos", type="filepath", elem_id='img-display-input')
> > **4. finally, line 254,**
> > submit_single = gr.Button(value="Compute Depth for Single Image", variant="primary",)
> > sorry if this was tedious, I'm not familiar with how this works and it's my first time posting/editing.
> 
> Thank you for trying. Unfortunately, the extension still doesn't work for me. I get the following error even after replacing the lines you mentioned:
> 
> *** Error loading script: upgraded_depth_anything_v2.py Traceback (most recent call last): File "E:\Private\stablediffusion\forge_new\webui\modules\scripts.py", line 544, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "E:\Private\stablediffusion\forge_new\webui\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "E:\Private\stablediffusion\forge_new\webui\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py", line 4, in from depth_anything_v2.dpt import DepthAnythingV2 ModuleNotFoundError: No module named 'depth_anything_v2.dpt'
> 
> Edit: May be related to using wrong file - testing again Edit2: This happens regardless of whether or not one uses the .7z or .zip file version of UDAV2 for forge.

id try deleting the venv folder and then download the sd forge zip again. I know that out the four links,  the top two are the ones that work. then start the webui up. Either this or you can try installing the module manually with cmd and pip. Im not entirely sure why it wouldnt work after doing all this.

**Comment by MackinationsAi** [comment]
![Screenshot 2024-07-30 at 15-47-06 Stable Diffusion](https://github.com/user-attachments/assets/bc423bf1-d54b-471b-a826-6b69031a7327)

Don't know why it isn't working for you all, I just reinstalled it myself & everything is working find. Here is the .zip I used. Try it out & hopefully you all will be back up & running!

[sd-forge-udav2.zip](https://github.com/user-attachments/files/16432823/sd-forge-udav2.zip)

**Comment by MackinationsAi** [comment]
@ropestra, @tnotariano & @franklydegenerate, please let me know if the above *sd-forge-udav2.zip* I attached yesterday worked if you were/are experiencing that error, so I can close out this issue ticket. Also @ropestra if it is still not appearing, try restart forge once or twice, sometimes bc forge is no longer being maintained it has given me similar errors when installing new extensions? If none of above fixes solve the error you're experiencing, I'm here to help troubleshoot further to get you up & running.

**Comment by franklydegenerate** [comment]
> @ropestra, @tnotariano & @franklydegenerate, please let me know if the above _sd-forge-udav2.zip_ I attached yesterday worked if you were/are experiencing that error, so I can close out this issue ticket. Also @ropestra if it is still not appearing, try restart forge once or twice, sometimes bc forge is no longer being maintained it has given me similar errors when installing new extensions? If none of above fixes solve the error you're experiencing, I'm here to help troubleshoot further to get you up & running.

**Sorry for the late reply! Thank you for your time, by the way. I just tested the .zip file that you provided, and I'm still getting this error upon launching the forge webui:** 

*** Error loading script: upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "E:\Private\stablediffusion\forge_new\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Private\stablediffusion\forge_new\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Private\stablediffusion\forge_new\webui\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py", line 4, in <module>
        from depth_anything_v2.dpt import DepthAnythingV2
    ModuleNotFoundError: No module named 'depth_anything_v2.dpt'

**Comment by MackinationsAi** [comment]
Try installing the sd-webui-udav2 from the extensions tab like you would normally do for a1111. Then once it is installed before you restart forge go to the sd-webui-udav2 extensions folder, then go into the scripts folder & replace upgraded_depth_anything_v2.py w/ this version - [upgraded_depth_anything_v2.md](https://github.com/user-attachments/files/16453010/upgraded_depth_anything_v2.md) [you will have to change the .md to .py as I can't upload .py scripts here]. Hopefully this sudo-patch works?

**Comment by franklydegenerate** [comment]
> Try installing the sd-webui-udav2 from the extensions tab like you would normally do for a1111. Then once it is installed before you restart forge go to the sd-webui-udav2 extensions folder, then go into the scripts folder & replace upgraded_depth_anything_v2.py w/ this version - [upgraded_depth_anything_v2.md](https://github.com/user-attachments/files/16453010/upgraded_depth_anything_v2.md) [you will have to change the .md to .py as I can't upload .py scripts here]. Hopefully this sudo-patch works?

-------
Thanks for trying to help! I'm not sure what could be going on here. After following the steps as you describe, I get something similar to before, if not the same:

*** Error loading script: upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "E:\Private\stablediffusion\forge_new\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Private\stablediffusion\forge_new\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Private\stablediffusion\forge_new\webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 5, in <module>
        from depth_anything_v2.dpt import DepthAnythingV2
    ModuleNotFoundError: No module named 'depth_anything_v2.dpt'

![image](https://github.com/user-attachments/assets/89fe95ce-12c5-4518-9e4c-48d862f02eaf)

**Comment by ropestra** [comment]
&gt; Try installing the sd-webui-udav2 from the extensions tab like you would normally do for a1111. Then once it is installed before you restart forge go to the sd-webui-udav2 extensions folder, then go into the scripts folder &amp; replace upgraded_depth_anything_v2.py w/ this version - [upgraded_depth_anything_v2.md](https://github.com/user-attachments/files/16453010/upgraded_depth_anything_v2.md) [you will have to change the .md to .py as I can't upload .py scripts here]. Hopefully this sudo-patch works?

Thanks for your help @MackinationsAi . Unfortunately like @franklydegenerate I followed the steps you indicate and the console shows me the same error: 

```
WARNING:dinov2:xFormers not available
WARNING:dinov2:xFormers not available
*** Error loading script: upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "F:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-udav2\scripts\upgraded_depth_anything_v2.py", line 5, in <module>
        from depth_anything_v2.dpt import DepthAnythingV2
    ModuleNotFoundError: No module named 'depth_anything_v2.dpt'
```
I'm not sure if xFormers is related, I really don't know.

**Comment by MackinationsAi** [comment]
Hey @tnotariano, @ropestra & @franklydegenerate 

So I did a fresh install of forge, updated the script to detect the depth_anything_v2.dpt module & installed the new extension. Tested it multiple times & everything worked each time I tested it. Here is the release of v0.0.5 [sd-forge-udav2](https://github.com/MackinationsAi/sd-webui-udav2/releases/tag/sd-forge-udav2_v0.0.5). 

Fingers crossed, it should now work for you all!

**Comment by franklydegenerate** [comment]
> Hey @tnotariano, @ropestra & @franklydegenerate
> 
> So I did a fresh install of forge, updated the script to detect the depth_anything_v2.dpt module & installed the new extension. Tested it multiple times & everything worked each time I tested it. Here is the release of v0.0.5 [sd-forge-udav2](https://github.com/MackinationsAi/sd-webui-udav2/releases/tag/sd-forge-udav2_v0.0.5).
> 
> Fingers crossed, it should now work for you all!

I'm thinking that it has to do with forge instead of your extension based on these lines in the screenshot. So sorry for troubling you with this! I'll have to try reinstalling or something.

![image](https://github.com/user-attachments/assets/567d5918-9a05-416d-bfa4-d6218173836e)

I'd love to switch to the base SD webui branch, but I dunno if there's anything like forge_couple for it. I really, really appreciate your time on this.

**Comment by MackinationsAi** [comment]
Have you updated forge? lllyasviel just updated it today, might help you get it up & running. Add ```git pull``` to the first line of your webui-user.bat file. Or just use the [stand-alone version](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2)!

**Comment by ropestra** [comment]
> Reference in n

I've read that many extensions stop working when updating the new version of Forge. :(

**Comment by MackinationsAi** [comment]
It worked on the new version, I installed the new version of forge to test it 3 hours ago, granted lllyasviel made a bunch of updates 2 hours ago so who knows. But seriously, if you all want to us UDAV2 you can use it outside of forge & a1111 w/ the original stant-alone version I made b4 converting it into an extension - [MackinationsAi/Upgraded-Depth-Anything-V2](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2)

**Comment by tnotariano** [comment]
sorry guys, I gave the wrong line numbers to edit, if you copy and replace these lines, it will work in the updated version.

use this zip as provided by the owner:  > [sd-forge-udav2.zip](https://github.com/user-attachments/files/16432823/sd-forge-udav2.zip)

here is what you do:
1. go into you sd forge folder and open this file in notepad: "stable-diffusion-webui-forge\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py"

2. edit these lines, change the whole line.

line 318: **input_videos = gr.Files(label="Input Videos", type="filepath", elem_id='img-display-input')**

lines 246-248, respectively:

 a. **input_image = gr.Image(label="Input Image", type='numpy', elem_id='img-display-input', height=794,)**

 b.  **depth_image_slider = gr.Image(label="Colourized Depth Map View", elem_id='img-display-output', height=794,)**

 c.  **grey_depth_file_single = gr.Image(label="Greyscale Depth Map View", elem_id='img-display-output', height=794,)**

line 254: **submit_single = gr.Button(value="Compute Depth for Single Image", variant="primary",)**

**Comment by ropestra** [comment]
> It worked on the new version, I installed the new version of forge to test it 3 hours ago, granted lllyasviel made a bunch of updates 2 hours ago so who knows. But seriously, if you all want to us UDAV2 you can use it outside of forge & a1111 w/ the original stant-alone version I made b4 converting it into an extension - [MackinationsAi/Upgraded-Depth-Anything-V2](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2)

I have noticed that it is not only with your extension, it also happens with others like LayerDifussion, but I was able to install IC-Ligth without problems, it is something strange.

`*** Error loading script: upgraded_depth_anything_v2.py
    Traceback (most recent call last):
      File "F:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\webui_forge_cu121_torch21\webui\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py", line 5, in <module>
        from depth_anything_v2.dpt import DepthAnythingV2
    ModuleNotFoundError: No module named 'depth_anything_v2.dpt'`

**Comment by tnotariano** [comment]
> It worked on the new version, I installed the new version of forge to test it 3 hours ago, granted lllyasviel made a bunch of updates 2 hours ago so who knows. But seriously, if you all want to us UDAV2 you can use it outside of forge & a1111 w/ the original stant-alone version I made b4 converting it into an extension - [MackinationsAi/Upgraded-Depth-Anything-V2](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2)

Hi if you read my latest comment, it shows a fix. Im not familiar with how tbis works, but can you edit the repository somehow?

**Comment by tnotariano** [comment]
> > It worked on the new version, I installed the new version of forge to test it 3 hours ago, granted lllyasviel made a bunch of updates 2 hours ago so who knows. But seriously, if you all want to us UDAV2 you can use it outside of forge & a1111 w/ the original stant-alone version I made b4 converting it into an extension - [MackinationsAi/Upgraded-Depth-Anything-V2](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2)
> 
> I have noticed that it is not only with your extension, it also happens with others like LayerDifussion, but I was able to install IC-Ligth without problems, it is something strange.
> 
> `*** Error loading script: upgraded_depth_anything_v2.py Traceback (most recent call last): File "F:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "F:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "F:\webui_forge_cu121_torch21\webui\extensions\sd-forge-udav2\scripts\upgraded_depth_anything_v2.py", line 5, in <module> from depth_anything_v2.dpt import DepthAnythingV2 ModuleNotFoundError: No module named 'depth_anything_v2.dpt'`

Yes im having trouble with many different extensions. Im trying to find the root of tbe problem

**Comment by MackinationsAi** [comment]
I think it's a combination of the latest gradio 4.40.0 update (which has a lot of depricated features now) & the fact that lllyasviel has been making **MAJOR** alterations to forge. Looks like we'll all have to wait until after Aug. 7th for a stabilized version to be released that will solve all *if not most* of the integration extension errors - [source-issue #933](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/933)

**Comment by tnotariano** [comment]
> I think it's a combination of the latest gradio 4.40.0 update (which has a lot of depricated features now) & the fact that lllyasviel has been making **MAJOR** alterations to forge. Looks like we'll all have to wait until after Aug. 7th for a stabilized version to be released that will solve all _if not most_ of the integration extension errors - [source-issue #933](https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/933)

The new gradio update is very nice though.

**Comment by MackinationsAi** [comment]
Definitely agree the gradio update is nice, I also really like lllyasviel's new Canvas feature for img2img & cnet in the forge update. Ended up upgrading it a bit, altered the input handling & UI... looks really crisp now!
